# Per-audit config lives in prompts/<audit>_config.json; do not edit this file per audit.
import argparse
import json
import os
import sys
from dotenv import load_dotenv

SYSTEM_PROMPT = (
    "You are a quantitative auditor hunting for lookahead bias, "
    "silent failures, schema mismatches, and statistical flaws in "
    "FX algorithmic trading infrastructure. You have access to the "
    "full codebase and documentation. Be exhaustive."
)

CONFIG_KEYS = (
    "files_to_audit",
    "docs_to_include",
    "prompt_path",
    "latest_adr",
    "output_path",
    "preview_path",
)


class PreflightError(Exception):
    """Raised when one or more configured audit paths do not exist."""


def load_config(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    missing = [k for k in CONFIG_KEYS if k not in cfg]
    if missing:
        raise SystemExit(
            "Config error — missing keys: " + ", ".join(missing)
        )
    return cfg


def preflight_check_paths(
    files_to_audit: dict[str, str],
    docs_to_include: dict[str, str],
    prompt_path: str,
    latest_adr: str | None,
) -> int:
    """Verify all configured paths exist before building or sending the audit prompt."""
    missing: list[tuple[str, str, str]] = []

    for key, path in files_to_audit.items():
        if not os.path.isfile(path):
            missing.append(("FILES_TO_AUDIT", key, path))

    for key, path in docs_to_include.items():
        if not os.path.isfile(path):
            missing.append(("DOCS_TO_INCLUDE", key, path))

    if not os.path.isfile(prompt_path):
        missing.append(("PROMPT_PATH", "PROMPT_PATH", prompt_path))

    if latest_adr is not None and not os.path.isfile(latest_adr):
        missing.append(("LATEST_ADR", "LATEST_ADR", latest_adr))

    if missing:
        lines = ["Preflight check FAILED — missing paths:"]
        for section, key, path in missing:
            lines.append(f"  [{section}] {key}: {path}")
        raise PreflightError("\n".join(lines))

    count = len(files_to_audit) + len(docs_to_include) + 1
    if latest_adr is not None:
        count += 1
    return count


def load_file(path: str, label: str, *, quiet: bool = False) -> str:
    if path is None:
        return ""
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        if not quiet:
            print(f"  Loaded: {label} ({len(content):,} chars)")
        return content
    except FileNotFoundError:
        if not quiet:
            print(f"  WARNING: {label} not found at {path} — skipping")
        return ""


def build_full_prompt(
    files_to_audit: dict[str, str],
    docs_to_include: dict[str, str],
    prompt_path: str,
    latest_adr: str | None,
    *,
    quiet: bool = False,
) -> str:
    prompt = load_file(prompt_path, "audit prompt", quiet=quiet)

    code_sections = []
    for label, path in files_to_audit.items():
        content = load_file(path, label, quiet=quiet)
        if content:
            code_sections.append(
                f"=== {label.upper()} ({path}) ===\n```cpp\n{content}\n```"
            )

    doc_sections = []
    for label, path in docs_to_include.items():
        content = load_file(path, label, quiet=quiet)
        if content:
            doc_sections.append(f"=== {label.upper()} ({path}) ===\n{content}")

    adr_content = load_file(latest_adr, "latest ADR", quiet=quiet) if latest_adr else ""
    if adr_content:
        doc_sections.append(f"=== LATEST ADR ({latest_adr}) ===\n{adr_content}")

    doc_block = "\n\n".join(doc_sections) if doc_sections else "(none)"
    code_block = "\n\n".join(code_sections) if code_sections else "(none)"
    return (
        prompt
        + "\n\n"
        + "## DOCUMENTATION\n\n"
        + doc_block
        + "\n\n"
        + "## CODE TO AUDIT\n\n"
        + code_block
    )


def build_messages(full_prompt: str) -> list[dict[str, str]]:
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": full_prompt},
    ]


def save_preview(
    files_to_audit: dict[str, str],
    docs_to_include: dict[str, str],
    prompt_path: str,
    latest_adr: str | None,
    output_path: str,
) -> int:
    """Build and save full API payload for human review. Does not call DeepSeek."""
    verified = preflight_check_paths(
        files_to_audit, docs_to_include, prompt_path, latest_adr
    )
    full_prompt = build_full_prompt(
        files_to_audit, docs_to_include, prompt_path, latest_adr, quiet=True
    )
    messages = build_messages(full_prompt)

    sections = [
        "# DeepSeek R1 Audit Preview (dry-run — not sent)\n",
        f"Preflight verified: {verified} paths\n",
        f"Total user message chars: {len(full_prompt):,}\n",
        "## System prompt\n",
        messages[0]["content"],
        "\n## User message\n",
        messages[1]["content"],
    ]
    body = "\n".join(sections)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(body)
    return len(body)


def run_r1_audit(
    cfg: dict,
    *,
    dry_run: bool = False,
    preview_path: str | None = None,
) -> None:
    files_to_audit = cfg["files_to_audit"]
    docs_to_include = cfg["docs_to_include"]
    prompt_path = cfg["prompt_path"]
    latest_adr = cfg["latest_adr"]
    output_path = cfg["output_path"]

    verified = preflight_check_paths(
        files_to_audit, docs_to_include, prompt_path, latest_adr
    )
    print(f"Preflight check passed: {verified} files verified\n")

    if dry_run or preview_path:
        target = preview_path or cfg["preview_path"]
        size = save_preview(
            files_to_audit,
            docs_to_include,
            prompt_path,
            latest_adr,
            target,
        )
        print(f"Dry-run preview saved: {target} ({size:,} chars)")
        print("No DeepSeek API call made.")
        return

    api_key = os.environ.get("DEEPSEEK_API_KEY")
    if not api_key:
        raise SystemExit(
            "DEEPSEEK_API_KEY is not set. "
            "Set it in the env file (default D:\\candlelab\\.env) or export it."
        )

    print("Loading files for audit...\n")
    full_prompt = build_full_prompt(
        files_to_audit, docs_to_include, prompt_path, latest_adr
    )
    print(f"\nTotal prompt size: {len(full_prompt):,} chars")
    print("Initiating DeepSeek-R1 Chain-of-Thought Audit. Please wait...\n")

    from openai import OpenAI

    client = OpenAI(
        api_key=api_key,
        base_url="https://api.deepseek.com",
    )

    response = client.chat.completions.create(
        model="deepseek-reasoner",
        messages=build_messages(full_prompt),
        timeout=600,
    )

    finish_reason = response.choices[0].finish_reason
    print(f"finish_reason={finish_reason}")

    reasoning = response.choices[0].message.reasoning_content or ""
    report = response.choices[0].message.content or ""

    if not report.strip():
        print("WARNING: Final report is empty (possible max output truncation).")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# DeepSeek R1 Audit Report\n\n")
        f.write("## Internal Reasoning\n\n")
        f.write(reasoning)
        f.write("\n\n## Final Report\n\n")
        f.write(report)
        f.write(f"\n\n<!-- finish_reason={finish_reason} -->\n")
    print(f"\nAudit saved to: {output_path}")

    print("=" * 50)
    print(" DEEPSEEK R1 INTERNAL REASONING")
    print("=" * 50)
    try:
        print(reasoning)
    except UnicodeEncodeError:
        print(reasoning.encode(sys.stdout.encoding or "utf-8", errors="replace").decode(
            sys.stdout.encoding or "utf-8", errors="replace"
        ))

    print("\n" + "=" * 50)
    print(" FINAL AUDIT REPORT")
    print("=" * 50)
    try:
        print(report)
    except UnicodeEncodeError:
        print(report.encode(sys.stdout.encoding or "utf-8", errors="replace").decode(
            sys.stdout.encoding or "utf-8", errors="replace"
        ))


def main() -> None:
    load_dotenv(os.environ.get("R1_ENV_FILE", r"D:\candlelab\.env"))

    parser = argparse.ArgumentParser(description="DeepSeek R1 audit runner")
    parser.add_argument(
        "--config",
        required=True,
        metavar="PATH",
        help="JSON file with files_to_audit, docs_to_include, prompt_path, etc.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Build full prompt preview without calling DeepSeek API",
    )
    parser.add_argument(
        "--preview",
        metavar="PATH",
        help="Save preview to PATH (implies --dry-run)",
    )
    args = parser.parse_args()
    cfg = load_config(args.config)
    try:
        run_r1_audit(
            cfg,
            dry_run=args.dry_run or bool(args.preview),
            preview_path=args.preview,
        )
    except PreflightError as exc:
        print(exc)
        raise SystemExit(1) from exc


if __name__ == "__main__":
    main()
